<?php

namespace App\Models;

use CodeIgniter\Model;

class ChatM extends Model
{
    protected $table = 'chat';
    protected $allowedFields = array('id_order', 'id_user', 'id_tukang', 'pesan');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = [
        'id_order' => 'required|max_length[10]',
        'id_user' => 'max_length[10]',
        'id_tukang' => 'max_length[10]',
        'pesan' => 'required|max_length[250]',
    ];

    protected $validationMessages = [
        'id_order' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 10 Karakter'],
        'id_user' => ['max_length' => 'Maximal 10 Karakter'],
        'id_tukang' => ['max_length' => 'Maximal 10 Karakter'],
        'pesan' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 250 Karakter'],
    ];
    private function _get_datatables()
    {
        $column_search = array('id_user', 'id_tukang', 'pesan');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file ChatM.php */
/* Location: ./app/models/ChatM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-05-17 08:40:53 */