<?php

namespace App\Models;

use CodeIgniter\Model;

class KategoriM extends Model
{
    protected $table = 'kategori';
    protected $allowedFields = array('nama_kategori', 'keterangan');
    protected $returnType     = 'object';

    protected $validationRules = [
        'nama_kategori' => 'required|max_length[50]',
    ];

    protected $validationMessages = [
        'nama_kategori' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 50 Karakter'],
    ];
    private function _get_datatables()
    {
        $column_search = array('nama_kategori', 'keterangan');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file TukangM.php */
/* Location: ./app/models/TukangM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-07 17:30:22 */